# Generated by Django 5.2.4 on 2025-08-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='helpful',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
