# Generated by Django 5.2.4 on 2025-08-16 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_scanhistory_helpful'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanhistory',
            old_name='helpful',
            new_name='feedback',
        ),
    ]
